exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/rofi/polkit-agent
exec-once = swaync
exec-once = hypridle & hyprsunset & hyprpaper & waybar
exec-once = 1password
exec-once = $terminal
