$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

source = ./hyprland/mocha.conf
source = ./hyprland/monitors.conf
source = ./hyprland/autostart.conf
source = ./hyprland/env.conf
source = ./hyprland/input.conf
source = ./hyprland/general.conf
source = ./hyprland/keybindings.conf
source = ./hyprland/windows.conf
